// <auto-generated />
namespace CodeEditorApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FileUpdate_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FileUpdate_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201705082058033_FileUpdate_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
